### ISSUE TITLE
React route prev/next links throuth rest api

### ISSUE THREAD

**Issue by conformist-mw** [bradwestfall/Learn-React#2]
Hi Brad!

I learn your awesome course about react and have a question. I made my own api by django and all works perfect but I want to add on page next/prev links to change pages one by one. So I a little bit dissapointed and don't understand how to accomplish that. My api looks like this:
```
count: 2302,
next: "http://localhost:8080/instant/api/?page=2",
previous: ,
results:
    0: Object,
    1: Object,
    2: Object.... (50 objects per page)
```
So general idea is simple singe page app that can change pages and show detailed info. All works well except page changes, I don't know how to use those links from my api and send them to Users props to make a new xhr request.

**Comment by bradwestfall** [comment]
I guess you would just take `next` part of your response and plug it into an anchor like this `<Link to={response.next}>`. I'm not sure if I understand the complexities of your question though

**Comment by conformist-mw** [comment]
Ok, maybe I explain not correctly. I want to create a single page browse of existing api. API returns me links and objects. When I open / link I see first page. State of component Users now is:
```
let Users = React.createClass({
  getInitialState: function(){
    return {
      link: 'http://localhost:8080/instant/api',
      users: [],
      previous: '',
      next: '',
      count: 0
    }
  },
  componentDidMount: function(){
    axios.get(this.state.link).then(xhr => {
      this.setState({
        users: xhr.data.results,
        previous: xhr.data.previous,
        next: xhr.data.next,
        count: xhr.data.count
      });
    })
  },
  render: ....
  ....
  ```
  On my first page I have objects and link to second page. In render I may insert `<Link to={this.state.next}>` and this link refer me to `http://localhost:8080/http://localhost:8080/instant/api/?page=2` and even when I hardcode proper link the Users component doesn't reload his state and doesn't show second page. What I attemp to do is like the carousel of pages but that carousel has first and last page. So this is not pagination. I have next link, click on it and in root div I have new content of the next page, this is a point.

**Comment by bradwestfall** [comment]
When this component mounts, the `componentDidMount` is only going to fire once. When the user clicks the link to go from page 1 or page 2, chances are you are having this component loaded for the second page too right? So in that case, if the URL changes and the same components are mounted for the route change, then the components will remain in place and will not be remounted. So this component will not experience several `componentDidMount`s every time you change the page. You probably need to consider other lifecycle hooks along with this one like `componentWillReceiveProps` or maybe React Router can tell you when the route changed. I don't mind helping pointing you in the right direction, but I would need to see a ton more of your code to debug your code with you. I won't have time to do that though. I hope that helped -- I think it's just that maybe you didn't know that `componentDidMount` won't be called twice

**Comment by conformist-mw** [comment]
I'm bad at explaining English :D
Ok, we have components `Users`, `User` and function getData, that have default link `http://swapi.io/api`. To get some particular user we create route `<Route path="/profile/:id" component={UserProfile} />`. `id` we got from User state. Like this I want to create `<Route path="/:page" component={Users} />` (something like this url based on real url `/?page=2`). Problem is how to pass Users.state.next from component that already mounted to route section? In `Users` component code something like `getData(base_url + this.props.params.page)`.
General picture:
```
Users.state:
    Users.prev
    |    Users.next
    |    |    Users.object.1 ----> base_url/1
    |    |    Users.object.2 ----> base_url/2
    |    |    Users.object.3 ----> base_url/3
    |    |    ......
    |    |    Users.object.n ----> base_url/n
    |    |
    |    Route to={Users.state.next.page} ----> base_url/page=2
    Route to={Users.state.prev.page} ----> base_url/null
```

**Comment by bradwestfall** [comment]
I'm sorry, I don't know how to help on this

**Comment by conformist-mw** [comment]
Hi Brad, I've solved my issue by adding new methods to Users component (componentWillReceiveProps, componentDidUpdate) and now all works perfect. Details in my [repo](https://github.com/conformist-mw/django_react/blob/master/assets/js/index.jsx) if you are interested. Cheers!

**Comment by bradwestfall** [comment]
Awesome, yea I figured it was a lifecycle issue. Great, good job
